// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::motorControlHindRight = NULL;
SpeedController* RobotMap::motorControlHindLeft = NULL;
SpeedController* RobotMap::motorControlFrontRight = NULL;
SpeedController* RobotMap::motorControlFrontLeft = NULL;
RobotDrive* RobotMap::motorControlRobotDrive = NULL;
DoubleSolenoid* RobotMap::pneumDoubleSolenoid = NULL;
Compressor* RobotMap::pneumCompressor = NULL;
Servo* RobotMap::servoControlerUpDown = NULL;
Servo* RobotMap::servoControlerRightLeft = NULL;
Gyro* RobotMap::sensorsGyro1 = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	motorControlHindRight = new Talon(2);
	lw->AddActuator("MotorControl", "HindRight", (Talon*) motorControlHindRight);
	
	motorControlHindLeft = new Jaguar(4);
	lw->AddActuator("MotorControl", "HindLeft", (Jaguar*) motorControlHindLeft);
	
	motorControlFrontRight = new Jaguar(1);
	lw->AddActuator("MotorControl", "FrontRight", (Jaguar*) motorControlFrontRight);
	
	motorControlFrontLeft = new Jaguar(3);
	lw->AddActuator("MotorControl", "FrontLeft", (Jaguar*) motorControlFrontLeft);
	
	motorControlRobotDrive = new RobotDrive(motorControlFrontLeft, motorControlHindLeft,
              motorControlFrontRight, motorControlHindRight);
	
	motorControlRobotDrive->SetSafetyEnabled(true);
        motorControlRobotDrive->SetExpiration(0.1);
        motorControlRobotDrive->SetSensitivity(0.5);
        motorControlRobotDrive->SetMaxOutput(1.0);

	pneumDoubleSolenoid = new DoubleSolenoid(0, 3, 2);      
	lw->AddActuator("Pneum", "DoubleSolenoid", pneumDoubleSolenoid);
	
	pneumCompressor = new Compressor(0);
	
	
	servoControlerUpDown = new Servo(6);
	lw->AddActuator("ServoControler", "UpDown", servoControlerUpDown);
	
	servoControlerRightLeft = new Servo(5);
	lw->AddActuator("ServoControler", "RightLeft", servoControlerRightLeft);
	
	sensorsGyro1 = new Gyro(0);
	lw->AddSensor("Sensors", "Gyro 1", sensorsGyro1);
	sensorsGyro1->SetSensitivity(0.007);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
