// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
Compressor* RobotMap::pneumCompressor = NULL;
DoubleSolenoid* RobotMap::pneumDoubleSolenoid = NULL;
SpeedController* RobotMap::motorControlTalonControler = NULL;
SpeedController* RobotMap::motorControlJaguarPort1 = NULL;
SpeedController* RobotMap::motorControlJaguarRightUpDown = NULL;
SpeedController* RobotMap::motorControlJaguarRightLeftRight = NULL;
RobotDrive* RobotMap::motorControlRobotDrive41 = NULL;
Servo* RobotMap::servoControlerServoUpDown = NULL;
Servo* RobotMap::servoControlerServoRightLeft = NULL;
Gyro* RobotMap::sensorsGyro = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
Counter* RobotMap::motorgt = NULL;

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	pneumCompressor = new Compressor(0);
	
	
	pneumDoubleSolenoid = new DoubleSolenoid(0, 3, 2);      
	lw->AddActuator("Pneum", "DoubleSolenoid", pneumDoubleSolenoid);
	
	motorControlTalonControler = new Talon(2);
	lw->AddActuator("MotorControl", "TalonControler", (Talon*) motorControlTalonControler);
	
	motorControlJaguarPort1 = new Jaguar(1);
	lw->AddActuator("MotorControl", "JaguarPort1", (Jaguar*) motorControlJaguarPort1);
	
	motorControlJaguarRightUpDown = new Jaguar(3);
	lw->AddActuator("MotorControl", "JaguarRightUpDown", (Jaguar*) motorControlJaguarRightUpDown);
	
	motorControlJaguarRightLeftRight = new Jaguar(4);
	lw->AddActuator("MotorControl", "JaguarRightLeftRight", (Jaguar*) motorControlJaguarRightLeftRight);
	
	motorControlRobotDrive41 = new RobotDrive(motorControlTalonControler, motorControlJaguarPort1,
              motorControlJaguarRightUpDown, motorControlJaguarRightLeftRight);
	
	motorControlRobotDrive41->SetSafetyEnabled(true);
        motorControlRobotDrive41->SetExpiration(0.1);
        motorControlRobotDrive41->SetSensitivity(0.5);
        motorControlRobotDrive41->SetMaxOutput(1.0);

	servoControlerServoUpDown = new Servo(6);
	lw->AddActuator("ServoControler", "ServoUpDown", servoControlerServoUpDown);
	
	servoControlerServoRightLeft = new Servo(5);
	lw->AddActuator("ServoControler", "ServoRightLeft", servoControlerServoRightLeft);
	
	sensorsGyro = new Gyro(0);
	lw->AddSensor("Sensors", "Gyro", sensorsGyro);
	sensorsGyro->SetSensitivity(0.007);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	//Counter(1);
}
