// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "MotorControl.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

MotorControl::MotorControl() : Subsystem("MotorControl") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	talonControler = RobotMap::motorControlTalonControler;
	jaguarPort1 = RobotMap::motorControlJaguarPort1;
	jaguarRightUpDown = RobotMap::motorControlJaguarRightUpDown;
	jaguarRightLeftRight = RobotMap::motorControlJaguarRightLeftRight;
	robotDrive41 = RobotMap::motorControlRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void MotorControl::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void MotorControl::TalonMove(float value){
	talonControler->Set(value);
}
void MotorControl::JaguarPort1(float value) {
	jaguarPort1->Set(value);
}
void MotorControl::JaguarRightUpDown(float value) {
	jaguarRightUpDown->Set(value);
}
void MotorControl::JagaurRightLeft(float value) {
	jaguarRightLeftRight->Set(value);
}

// Put methods for controlling this subsystem
// here. Call these from Commands.

