// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef MOTORCONTROL_H
#define MOTORCONTROL_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class MotorControl: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* talonControler;
	SpeedController* jaguarPort1;
	SpeedController* jaguarRightUpDown;
	SpeedController* jaguarRightLeftRight;
	RobotDrive* robotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	MotorControl();
	void InitDefaultCommand();
	void TalonMove(float value);
	void JaguarPort1(float value);
	void JaguarRightUpDown(float value);
	void JagaurRightLeft(float value);
};

#endif
