// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Level3.h"

Level3::Level3() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::motorControl);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void Level3::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void Level3::Execute() {
	if (Robot::sensors->encoder->Get() >= 1100 ) {
	Robot::motorControl->hindRight->Set(-.5);
	} else {
		Robot::motorControl->hindRight->Set(.5);
	}

	printf("%i\n",Robot::sensors->encoder->Get());
}

// Make this return true when this Command no longer needs to run execute()
bool Level3::IsFinished() {
	int z;
	z = Robot::sensors->encoder->Get();
	bool x;
	if (z <= 900 and z >= 1100) {
		x = true;
	}
	return x;
}

// Called once after isFinished returns true
void Level3::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Level3::Interrupted() {

}
