// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef MOTORCONTROL_H
#define MOTORCONTROL_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class MotorControl: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* hindRight;
	SpeedController* hindLeft;
	SpeedController* frontRight;
	SpeedController* frontLeft;
	RobotDrive* robotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	MotorControl();
	void InitDefaultCommand();
	void InitMecanum(uint32_t  frontLeftMotor,
			  uint32_t  rearLeftMotor,
			  uint32_t  frontRightMotor,
			  uint32_t  rearRightMotor);
	/*void Forward(float value);
	void Backward(float value);
	void Left(float value);
	void Right(float value);*/
};

#endif
