// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Camera.h"
#include "Commands/GyroCommand.h"
#include "Commands/MotorRun.h"
#include "Commands/ServoCommand.h"
#include "Commands/pPushIn.h"
#include "Commands/pPushOut.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	xbox = new Joystick(0);
	
	joystickButton5 = new JoystickButton(xbox, 5);
	joystickButton5->WhenPressed(new GyroCommand());
	joystickButton4 = new JoystickButton(xbox, 4);
	joystickButton4->WhenPressed(new ServoCommand());
	joystickButton3 = new JoystickButton(xbox, 3);
	joystickButton3->WhenPressed(new MotorRun());
	joystickButton2 = new JoystickButton(xbox, 2);
	joystickButton2->WhenPressed(new pPushIn());
	joystickButton1 = new JoystickButton(xbox, 1);
	joystickButton1->WhenPressed(new pPushOut());
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("MotorRun", new MotorRun());

	SmartDashboard::PutData("pPushIn", new pPushIn());

	SmartDashboard::PutData("pPushOut", new pPushOut());

	SmartDashboard::PutData("ServoCommand", new ServoCommand());

	SmartDashboard::PutData("GyroCommand", new GyroCommand());

	SmartDashboard::PutData("Camera", new Camera());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getXbox() {
	return xbox;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
